import type { CoreServicePageContent } from "@/components/v3/service-core-template";

type HubCard = {
  image: string;
  title: string;
  description: string;
  tags: string[];
  href: string;
};

const imageA = "https://www.figma.com/api/mcp/asset/bf706c23-7980-40ad-bdde-cc07889049d7";
const imageB = "https://www.figma.com/api/mcp/asset/893d0773-3792-4b30-ac20-536e15a6d304";
const imageC = "https://www.figma.com/api/mcp/asset/25e2ad1f-ac04-45b5-8c28-25e7f86ad754";

export const servicesHubCards: HubCard[] = [
  { image: imageA, title: "Web Design", description: "Professional websites built to generate qualified leads.", tags: ["Lead capture", "Conversion-first", "Modern UI"], href: "/web-design" },
  { image: imageB, title: "Website Development", description: "Fast, scalable implementation with SEO-ready foundations.", tags: ["Performance", "Technical SEO", "Scalable"], href: "/web-development" },
  { image: imageC, title: "Landing Pages", description: "Focused pages for offers, campaigns, and WhatsApp conversions.", tags: ["Campaign-ready", "High intent", "Conversion"], href: "/landing-page-design" },
  { image: imageA, title: "Ecommerce Websites", description: "Stores designed to improve product discovery and checkout conversion.", tags: ["Ecommerce UX", "Checkout flow", "Revenue growth"], href: "/ecommerce-websites" },
  { image: imageB, title: "Website Redesign", description: "Redesign outdated websites into high-performing lead engines.", tags: ["Repositioning", "Trust", "Conversion"], href: "/website-redesign" },
  { image: imageC, title: "Maintenance and Support", description: "Ongoing improvements, updates, and technical support for continuity.", tags: ["Support", "Stability", "Optimization"], href: "/maintenance-support" },
  { image: imageA, title: "Custom Website Solutions", description: "Tailored architecture for advanced business models and workflows.", tags: ["Custom features", "Integrations", "Multi-location"], href: "/custom-website-solutions" },
];

export const industriesHubCards: HubCard[] = [
  { image: imageA, title: "Real Estate", description: "Showcase properties and capture qualified buyer inquiries.", tags: ["Listings", "Trust", "Lead flow"], href: "/industries/real-estate" },
  { image: imageB, title: "Villas & Vacation Rentals", description: "Premium pages with booking inquiry and WhatsApp conversion.", tags: ["Bookings", "Visual trust", "Mobile-first"], href: "/industries/villas-vacation-rentals" },
  { image: imageC, title: "Restaurants", description: "Web experiences for reservations, delivery, and local visibility.", tags: ["Menus", "Reservations", "Maps"], href: "/industries/restaurants" },
  { image: imageA, title: "Excursions & Tours", description: "Packages and itinerary pages that increase booking requests.", tags: ["Packages", "Reviews", "Booking CTA"], href: "/industries/excursions-tours" },
  { image: imageB, title: "Wellness / Spa / Beauty", description: "Premium brand presence with appointment-oriented conversion.", tags: ["Appointments", "Service menus", "Branding"], href: "/industries/wellness-spa-beauty" },
  { image: imageC, title: "Aesthetic or Dental Clinics", description: "Authority-focused layouts with consultation and booking pathways.", tags: ["Authority", "Consultation", "Local SEO"], href: "/industries/aesthetic-dental-clinics" },
  { image: imageA, title: "Lawyers & Premium Services", description: "Credibility-first pages that support higher-value inquiries.", tags: ["Trust", "Premium tone", "Consultation"], href: "/industries/lawyers-premium-services" },
  { image: imageB, title: "Construction & Developments", description: "Project showcase pages with investor and buyer lead capture.", tags: ["Projects", "Investor leads", "Credibility"], href: "/industries/construction-real-estate-developments" },
  { image: imageC, title: "Tourism Businesses", description: "Multilingual-ready structures with inquiry and conversion blocks.", tags: ["Tourism intent", "WhatsApp", "Storytelling"], href: "/industries/tourism-businesses" },
];

export const locationsHubCards: HubCard[] = [
  { image: imageA, title: "Punta Cana", description: "Web design for local businesses that need more qualified leads.", tags: ["Tourism", "Real estate", "Local trust"], href: "/locations/punta-cana" },
  { image: imageB, title: "Dominican Republic", description: "Growth-focused websites for businesses across the Dominican market.", tags: ["National visibility", "Lead generation", "Professional image"], href: "/locations/dominican-republic" },
  { image: imageC, title: "Santiago", description: "Conversion-focused sites for fast-growing local service businesses.", tags: ["Local search", "Mobile UX", "Inquiries"], href: "/locations/santiago" },
  { image: imageA, title: "Miami", description: "Premium web design for businesses that compete in high-demand markets.", tags: ["Premium", "Performance", "Positioning"], href: "/locations/miami" },
  { image: imageB, title: "Orlando", description: "Websites for local services that need consistent client acquisition.", tags: ["Service businesses", "Lead flow", "Conversion"], href: "/locations/orlando" },
];

const defaultProcess = [
  { step: "Step 01", title: "Strategy", description: "We align your offer, target market, and conversion goals." },
  { step: "Step 02", title: "Design", description: "We design clear, trust-building sections for high-intent users." },
  { step: "Step 03", title: "Development", description: "We build a fast and SEO-ready website experience." },
  { step: "Step 04", title: "Launch", description: "We launch, test conversion points, and refine performance." },
];

function buildEntityPage({
  slug,
  metadataTitle,
  metadataDescription,
  h1,
  heroBadge,
  heroLineOne,
  heroLineTwo,
  heroSubtitle,
  whoTitle,
  whoSubtitle,
  whoItems,
  includesTitle,
  includesSubtitle,
  includeItems,
  benefitsTitle,
  benefitsSubtitle,
  benefitItems,
  faqs,
  recommendedPlan = "Business",
}: {
  slug: string;
  metadataTitle: string;
  metadataDescription: string;
  h1: string;
  heroBadge: string;
  heroLineOne: string;
  heroLineTwo: string;
  heroSubtitle: string;
  whoTitle: string;
  whoSubtitle: string;
  whoItems: { title: string; description: string }[];
  includesTitle: string;
  includesSubtitle: string;
  includeItems: { icon: "broadcast" | "framework" | "performance" | "ecosystem"; title: string; description: string }[];
  benefitsTitle: string;
  benefitsSubtitle: string;
  benefitItems: { title: string; description: string }[];
  faqs: { question: string; answer: string }[];
  recommendedPlan?: string;
}): CoreServicePageContent {
  return {
    slug,
    metadataTitle,
    metadataDescription,
    hero: {
      h1,
      badgeText: heroBadge,
      titleLineOne: heroLineOne,
      titleLineTwo: heroLineTwo,
      subtitle: heroSubtitle,
      ratingText: "Built for SEO visibility and qualified lead generation",
      backgroundImage: "https://www.figma.com/api/mcp/asset/eaf9e64e-7cc6-4116-97b0-8555d3cae1c5",
    },
    audienceTitle: whoTitle,
    audienceSubtitle: whoSubtitle,
    audienceItems: whoItems,
    deliverables: {
      eyebrow: "What the service includes",
      titleLineOne: includesTitle,
      titleLineTwo: "built to convert",
      subtitle: includesSubtitle,
      image: "https://www.figma.com/api/mcp/asset/675ae58d-5522-453d-a408-b4a8b5a01ab5",
      items: includeItems,
    },
    benefitsTitle,
    benefitsSubtitle,
    benefitsItems: benefitItems,
    outcomesTitle: "Business outcomes this page structure is designed to drive",
    outcomesSubtitle: "We optimize for qualified inquiries, stronger trust, and faster decision-making.",
    processTitle: "Our work process",
    processSubtitle: "A simple, transparent process designed for speed and conversion.",
    processSteps: defaultProcess,
    recommendedPlan,
    ctaBanner: {
      badgeText: "Ready to grow your pipeline?",
      titleLineOne: "Request your",
      titleLineTwo: "proposal today",
      subtitle: "Get a practical roadmap for your business, market, and conversion goals.",
      ratingText: "Conversion-focused implementation with transparent pricing",
      backgroundImage: "https://www.figma.com/api/mcp/asset/4f3985a6-d756-48a4-8db6-cd3dba920c9f",
    },
    faqs,
    finalCta: {
      title: "Tell us about your business and goals",
      subtitle: "We will send a proposal focused on lead generation, conversion, and long-term scalability.",
      bullets: [
        "Conversion-oriented section strategy",
        "Mobile-first UX and local SEO structure",
        "Request Proposal + WhatsApp lead flows",
        "Transparent plan recommendation",
      ],
    },
    relatedServices: {
      title: "Explore related pages",
      subtitle: "Keep navigating by service, industry, and location.",
      cards: [...servicesHubCards.slice(0, 3)],
    },
  };
}

export const industryPageContent: Record<string, CoreServicePageContent> = {
  "real-estate": buildEntityPage({
    slug: "real-estate",
    metadataTitle: "Website Design for Real Estate | Lead Generation Websites",
    metadataDescription: "Web design for real estate businesses focused on property leads, trust, and WhatsApp conversion.",
    h1: "Website design for real estate businesses",
    heroBadge: "Industry · Real Estate",
    heroLineOne: "Real estate websites",
    heroLineTwo: "built to generate qualified inquiries",
    heroSubtitle: "Showcase listings, build trust with buyers, and improve WhatsApp and form conversions.",
    whoTitle: "Who this is for in real estate",
    whoSubtitle: "Ideal for agencies, brokers, and property developers selling locally and internationally.",
    whoItems: [
      { title: "Real estate agencies", description: "Need better lead capture for listings and buyer consultations." },
      { title: "Developers", description: "Need project pages with stronger trust and investor inquiry flow." },
      { title: "Independent brokers", description: "Need authority and mobile-first inquiry pathways." },
    ],
    includesTitle: "Property-focused website systems",
    includesSubtitle: "Built to present inventory clearly and convert high-intent buyers.",
    includeItems: [
      { icon: "broadcast", title: "Listing-ready page structure", description: "Organize properties by type and buyer intent." },
      { icon: "framework", title: "Trust and proof blocks", description: "Showcase projects, testimonials, and credibility signals." },
      { icon: "performance", title: "Mobile inquiry optimization", description: "Capture contact intent on mobile without friction." },
      { icon: "ecosystem", title: "WhatsApp and form flow", description: "Connect conversations with your sales process." },
    ],
    benefitsTitle: "Why this helps real estate teams close faster",
    benefitsSubtitle: "Better structure and messaging improve lead quality and response speed.",
    benefitItems: [
      { title: "More qualified property inquiries", description: "Attract buyers with clear intent and budget alignment." },
      { title: "Stronger international trust", description: "Premium design supports buyers making remote decisions." },
      { title: "Faster lead response workflows", description: "WhatsApp and forms support immediate follow-up." },
    ],
    faqs: [
      { question: "Can this support property listing pages?", answer: "Yes. We structure pages for property categories, highlights, and lead capture." },
      { question: "Do you include WhatsApp contact points?", answer: "Yes. We integrate multiple WhatsApp touchpoints for higher response rate." },
      { question: "Can this work for luxury properties?", answer: "Yes. We adapt visual tone and structure for premium buyer expectations." },
    ],
  }),
  "villas-vacation-rentals": buildEntityPage({
    slug: "villas-vacation-rentals",
    metadataTitle: "Website Design for Villas & Vacation Rentals",
    metadataDescription: "Premium websites for villas and vacation rentals with booking inquiry flow and WhatsApp conversion.",
    h1: "Website design for villas and vacation rentals",
    heroBadge: "Industry · Villas & Vacation Rentals",
    heroLineOne: "Villa and rental websites",
    heroLineTwo: "that increase booking inquiries",
    heroSubtitle: "Premium galleries, trust blocks, and booking-focused CTA flows for better occupancy results.",
    whoTitle: "Who this is for in the rental market",
    whoSubtitle: "Designed for hosts, operators, and property managers who want more direct inquiries.",
    whoItems: [
      { title: "Villa operators", description: "Need premium pages to justify pricing and increase direct demand." },
      { title: "Property managers", description: "Need consistent inquiry flow across multiple listings." },
      { title: "Vacation rental brands", description: "Need trust-first digital presence for international guests." },
    ],
    includesTitle: "Booking-oriented website architecture",
    includesSubtitle: "Designed for visual trust and faster inquiry action.",
    includeItems: [
      { icon: "broadcast", title: "Premium gallery structure", description: "Highlight property experience with clear visual hierarchy." },
      { icon: "framework", title: "Availability and inquiry UX", description: "Guide users from browsing to booking request." },
      { icon: "performance", title: "Mobile-first traveler flow", description: "Capture intent quickly from mobile tourists." },
      { icon: "ecosystem", title: "WhatsApp booking path", description: "Shorten the path from interest to conversation." },
    ],
    benefitsTitle: "Why this drives more direct bookings",
    benefitsSubtitle: "Conversion-focused pages help reduce reliance on third-party platforms.",
    benefitItems: [
      { title: "More direct inquiries", description: "Increase direct communication channels with potential guests." },
      { title: "Higher perceived value", description: "Premium visuals support stronger nightly rates." },
      { title: "Better response speed", description: "Integrated contact paths accelerate booking conversations." },
    ],
    faqs: [
      { question: "Can this include booking inquiry forms?", answer: "Yes. We build forms specifically for booking and availability requests." },
      { question: "Can we highlight multiple properties?", answer: "Yes. We can structure multi-property navigation and detail pages." },
      { question: "Do you optimize for mobile travelers?", answer: "Yes. Mobile conversion flow is a core requirement in this industry." },
    ],
  }),
  restaurants: buildEntityPage({
    slug: "restaurants",
    metadataTitle: "Website Design for Restaurants | Reservations and Orders",
    metadataDescription: "Restaurant website design focused on reservations, menus, maps, and WhatsApp conversion.",
    h1: "Website design for restaurants",
    heroBadge: "Industry · Restaurants",
    heroLineOne: "Restaurant websites",
    heroLineTwo: "that increase reservations",
    heroSubtitle: "Clear menus, booking pathways, and local trust sections designed for more reservations and orders.",
    whoTitle: "Who this is for in hospitality",
    whoSubtitle: "For restaurants that need stronger local visibility and reservation flow.",
    whoItems: [
      { title: "Independent restaurants", description: "Need better direct reservations and local visibility." },
      { title: "Restaurant groups", description: "Need consistent structure across multiple locations." },
      { title: "Concept brands", description: "Need premium digital presence aligned to in-person experience." },
    ],
    includesTitle: "Restaurant conversion essentials",
    includesSubtitle: "Built to help guests decide and book faster.",
    includeItems: [
      { icon: "broadcast", title: "Menu and service sections", description: "Present menu, experience, and value clearly." },
      { icon: "framework", title: "Reservation-first layout", description: "Prioritize booking actions throughout the page." },
      { icon: "performance", title: "Location and map UX", description: "Help guests find and trust your location quickly." },
      { icon: "ecosystem", title: "WhatsApp and ordering links", description: "Drive direct contact and reduce friction." },
    ],
    benefitsTitle: "Why this improves restaurant demand",
    benefitsSubtitle: "Great UX and clear messaging increase action from local search traffic.",
    benefitItems: [
      { title: "More reservations", description: "Stronger CTA structure improves booking intent conversion." },
      { title: "Better local SEO relevance", description: "Pages structured for local restaurant search behavior." },
      { title: "Higher trust before visit", description: "Visual and social proof reduce decision hesitation." },
    ],
    faqs: [
      { question: "Can this include online reservation links?", answer: "Yes. We integrate reservation pathways and prominent booking CTAs." },
      { question: "Can we show menu updates easily?", answer: "Yes. We can set up editable menu sections and content blocks." },
      { question: "Do you support WhatsApp ordering contact?", answer: "Yes. We include WhatsApp conversion touchpoints where relevant." },
    ],
  }),
  "excursions-tours": buildEntityPage({
    slug: "excursions-tours",
    metadataTitle: "Website Design for Excursions and Tours",
    metadataDescription: "Websites for excursion and tour businesses with package showcase and booking inquiry conversion flows.",
    h1: "Website design for excursions and tours",
    heroBadge: "Industry · Excursions & Tours",
    heroLineOne: "Tour websites",
    heroLineTwo: "that convert interest into bookings",
    heroSubtitle: "Present packages clearly, build trust quickly, and increase booking inquiries through forms and WhatsApp.",
    whoTitle: "Who this is for in tours",
    whoSubtitle: "For tour operators that need stronger conversion from tourist traffic.",
    whoItems: [
      { title: "Local tour operators", description: "Need package pages that convert browsing into inquiries." },
      { title: "Adventure and excursion brands", description: "Need visual storytelling with clear booking actions." },
      { title: "Experience companies", description: "Need multilingual-friendly structure and trust proof." },
    ],
    includesTitle: "Booking-first tour page system",
    includesSubtitle: "Built for package visibility, trust, and faster decision-making.",
    includeItems: [
      { icon: "broadcast", title: "Package showcase layout", description: "Show itinerary highlights and value clearly." },
      { icon: "framework", title: "Trust and review blocks", description: "Reinforce decision confidence with social proof." },
      { icon: "performance", title: "Mobile tourist experience", description: "Support quick inquiry flow from mobile users." },
      { icon: "ecosystem", title: "Booking inquiry channels", description: "Connect forms and WhatsApp for immediate contact." },
    ],
    benefitsTitle: "Why this boosts bookings and inquiry quality",
    benefitsSubtitle: "Clear package pages attract better-fit travelers ready to book.",
    benefitItems: [
      { title: "More package inquiries", description: "Offer clarity increases contact intent from qualified visitors." },
      { title: "Higher booking trust", description: "Proof and structure reduce hesitation for new customers." },
      { title: "Better operational flow", description: "Lead details from forms improve booking follow-up." },
    ],
    faqs: [
      { question: "Can we include multiple tour packages?", answer: "Yes. We can structure pages by package type and audience intent." },
      { question: "Do you support multilingual-ready layouts?", answer: "Yes. We design for future multilingual expansion." },
      { question: "Can we prioritize WhatsApp bookings?", answer: "Yes. WhatsApp can be a primary conversion pathway." },
    ],
  }),
  "wellness-spa-beauty": buildEntityPage({
    slug: "wellness-spa-beauty",
    metadataTitle: "Website Design for Wellness, Spas, and Beauty Brands",
    metadataDescription: "Premium websites for wellness and beauty businesses with appointment-driven conversion structure.",
    h1: "Website design for wellness, spa, and beauty businesses",
    heroBadge: "Industry · Wellness / Spa / Beauty",
    heroLineOne: "Wellness websites",
    heroLineTwo: "that drive appointment requests",
    heroSubtitle: "Premium visual direction and conversion-focused page flow designed to increase consultations and bookings.",
    whoTitle: "Who this is for in wellness",
    whoSubtitle: "For brands where trust, visual quality, and appointment flow matter.",
    whoItems: [
      { title: "Spas and wellness centers", description: "Need premium brand presence and clearer service offers." },
      { title: "Beauty clinics and studios", description: "Need appointment-focused pages with trust cues." },
      { title: "Personal care brands", description: "Need stronger conversion from social and search traffic." },
    ],
    includesTitle: "Appointment-focused website structure",
    includesSubtitle: "Built for premium perception and action-oriented booking flow.",
    includeItems: [
      { icon: "broadcast", title: "Service menu architecture", description: "Present treatments with clarity and confidence." },
      { icon: "framework", title: "Premium visual hierarchy", description: "Align digital design with premium service positioning." },
      { icon: "performance", title: "Mobile consultation UX", description: "Capture consultation intent from mobile users." },
      { icon: "ecosystem", title: "Appointment CTA system", description: "Guide users into booking and inquiry pathways." },
    ],
    benefitsTitle: "Why this improves appointment volume",
    benefitsSubtitle: "A premium, clear website increases trust and conversion rate.",
    benefitItems: [
      { title: "More consultation requests", description: "Stronger CTA placement increases booking intent." },
      { title: "Better premium positioning", description: "Visual direction supports higher-value service perception." },
      { title: "Improved follow-up quality", description: "Better lead details improve sales conversations." },
    ],
    faqs: [
      { question: "Can this include treatment-specific pages?", answer: "Yes. We can structure service pages by treatment and intent." },
      { question: "Can we prioritize consultation bookings?", answer: "Yes. We design conversion flow around your priority service actions." },
      { question: "Is this mobile-first for social traffic?", answer: "Yes. Mobile-first behavior is a core part of our approach." },
    ],
  }),
  "aesthetic-dental-clinics": buildEntityPage({
    slug: "aesthetic-dental-clinics",
    metadataTitle: "Website Design for Aesthetic and Dental Clinics",
    metadataDescription: "Authority-focused websites for aesthetic and dental clinics with consultation and appointment conversion pathways.",
    h1: "Website design for aesthetic and dental clinics",
    heroBadge: "Industry · Aesthetic or Dental Clinics",
    heroLineOne: "Clinic websites",
    heroLineTwo: "built for trust and appointments",
    heroSubtitle: "Design and structure focused on credibility, service clarity, and higher consultation requests.",
    whoTitle: "Who this is for in healthcare services",
    whoSubtitle: "For clinics that need stronger trust and higher-quality patient inquiries.",
    whoItems: [
      { title: "Aesthetic clinics", description: "Need premium presentation and consultation-first conversion flow." },
      { title: "Dental clinics", description: "Need service clarity, doctor trust, and appointment pathways." },
      { title: "Multi-doctor clinics", description: "Need clear team and treatment architecture online." },
    ],
    includesTitle: "Trust-first clinic website system",
    includesSubtitle: "Designed to improve consultation quality and patient confidence.",
    includeItems: [
      { icon: "broadcast", title: "Doctor and clinic authority blocks", description: "Build confidence before first contact." },
      { icon: "framework", title: "Treatment/service architecture", description: "Make options understandable and actionable." },
      { icon: "performance", title: "Local intent optimization", description: "Support patients searching for nearby providers." },
      { icon: "ecosystem", title: "Consultation lead flow", description: "Capture appointments via form and WhatsApp." },
    ],
    benefitsTitle: "Why this improves patient acquisition",
    benefitsSubtitle: "Trust, clarity, and conversion flow are critical for clinic websites.",
    benefitItems: [
      { title: "Higher consultation requests", description: "Clear offers and CTA placement improve appointment intent." },
      { title: "More professional positioning", description: "Authority-driven layout improves patient confidence." },
      { title: "Better local search relevance", description: "Structure supports local intent and service visibility." },
    ],
    faqs: [
      { question: "Can we include team/doctor profiles?", answer: "Yes. We can create dedicated credibility sections for doctors and specialists." },
      { question: "Can this support multiple treatments?", answer: "Yes. We structure treatment pages for clarity and conversion." },
      { question: "Do you optimize for local clinic searches?", answer: "Yes. Local-intent structure is included in our SEO approach." },
    ],
  }),
  "lawyers-premium-services": buildEntityPage({
    slug: "lawyers-premium-services",
    metadataTitle: "Website Design for Lawyers and Premium Services",
    metadataDescription: "Authority-driven websites for lawyers and premium services focused on high-value inquiry conversion.",
    h1: "Website design for lawyers and premium service businesses",
    heroBadge: "Industry · Lawyers & Premium Services",
    heroLineOne: "Authority-focused websites",
    heroLineTwo: "for premium service firms",
    heroSubtitle: "Premium positioning, clear service framing, and conversion pathways for high-value consultations.",
    whoTitle: "Who this is for in premium services",
    whoSubtitle: "For firms where trust, expertise, and conversion quality drive revenue.",
    whoItems: [
      { title: "Law firms", description: "Need stronger authority and consultation flow online." },
      { title: "Private advisory firms", description: "Need premium positioning and high-trust digital experience." },
      { title: "High-ticket service brands", description: "Need pages that qualify and convert better-fit clients." },
    ],
    includesTitle: "Premium consultation conversion structure",
    includesSubtitle: "Built for authority, clarity, and qualified inquiry intent.",
    includeItems: [
      { icon: "broadcast", title: "Authority-first messaging", description: "Highlight expertise and differentiation clearly." },
      { icon: "framework", title: "Service category architecture", description: "Help visitors find the right service quickly." },
      { icon: "performance", title: "Premium UX consistency", description: "Design quality aligned with high-value positioning." },
      { icon: "ecosystem", title: "Consultation CTA flow", description: "Drive proposal and consultation requests effectively." },
    ],
    benefitsTitle: "Why this improves high-value lead quality",
    benefitsSubtitle: "Premium buyers evaluate trust signals before making contact.",
    benefitItems: [
      { title: "Better consultation leads", description: "Clear qualification flow reduces low-intent inquiries." },
      { title: "Stronger authority perception", description: "Digital presence matches premium market expectations." },
      { title: "Higher conversion confidence", description: "Users understand services and next steps faster." },
    ],
    faqs: [
      { question: "Can this include multiple legal practice areas?", answer: "Yes. We can structure pages by service category and intent." },
      { question: "Can we maintain a premium visual tone?", answer: "Yes. Visual direction is aligned to authority and high-value positioning." },
      { question: "Can we prioritize consultation forms?", answer: "Yes. CTA strategy centers on proposal and consultation conversion." },
    ],
  }),
  "construction-real-estate-developments": buildEntityPage({
    slug: "construction-real-estate-developments",
    metadataTitle: "Website Design for Construction and Real Estate Developments",
    metadataDescription: "Professional websites for construction firms and developers with project showcase and investor lead flow.",
    h1: "Website design for construction companies and developments",
    heroBadge: "Industry · Construction & Developments",
    heroLineOne: "Construction websites",
    heroLineTwo: "that build trust and pipeline",
    heroSubtitle: "Project showcase, credibility blocks, and inquiry systems for buyers, investors, and partners.",
    whoTitle: "Who this is for in construction",
    whoSubtitle: "For firms that need stronger digital trust to support sales and partnerships.",
    whoItems: [
      { title: "Construction firms", description: "Need project visibility and better commercial lead capture." },
      { title: "Real estate developers", description: "Need investor and buyer inquiry pathways online." },
      { title: "Engineering and contracting teams", description: "Need authority and structured service communication." },
    ],
    includesTitle: "Project-led website framework",
    includesSubtitle: "Built to present capabilities and convert high-value opportunities.",
    includeItems: [
      { icon: "broadcast", title: "Project portfolio system", description: "Showcase completed and active developments professionally." },
      { icon: "framework", title: "Service capability sections", description: "Clarify specialties and business scope quickly." },
      { icon: "performance", title: "Trust and authority layout", description: "Highlight certifications, experience, and proof points." },
      { icon: "ecosystem", title: "Inquiry and investor flow", description: "Capture serious leads through structured contact paths." },
    ],
    benefitsTitle: "Why this improves project-related opportunities",
    benefitsSubtitle: "A professional website helps convert credibility into commercial conversations.",
    benefitItems: [
      { title: "More qualified inquiries", description: "Capture buyers, investors, and partners with clearer intent." },
      { title: "Stronger project trust", description: "Detailed showcase supports decision confidence." },
      { title: "Better commercial positioning", description: "Present your company as structured and investment-ready." },
    ],
    faqs: [
      { question: "Can we highlight multiple projects and phases?", answer: "Yes. We can structure projects by category, phase, and location." },
      { question: "Can this support investor-focused sections?", answer: "Yes. We can include dedicated sections for investment and partnership leads." },
      { question: "Do you include inquiry forms for project leads?", answer: "Yes. We build forms and WhatsApp pathways tailored to project workflows." },
    ],
  }),
  "tourism-businesses": buildEntityPage({
    slug: "tourism-businesses",
    metadataTitle: "Website Design for Tourism Businesses",
    metadataDescription: "Conversion-focused websites for tourism businesses with visual storytelling and inquiry-driven structure.",
    h1: "Website design for tourism businesses",
    heroBadge: "Industry · Tourism Businesses",
    heroLineOne: "Tourism websites",
    heroLineTwo: "built for inquiry conversion",
    heroSubtitle: "Visual storytelling, service presentation, and conversion blocks for tourism-driven demand.",
    whoTitle: "Who this is for in tourism",
    whoSubtitle: "For tourism brands that need stronger digital conversion from local and international audiences.",
    whoItems: [
      { title: "Hospitality and experience brands", description: "Need visual-first pages with clear inquiry actions." },
      { title: "Destination businesses", description: "Need local relevance and trust for visitors." },
      { title: "Multi-service tourism operators", description: "Need structured service presentation across offers." },
    ],
    includesTitle: "Tourism-focused conversion architecture",
    includesSubtitle: "Built to inspire trust and drive inquiry actions quickly.",
    includeItems: [
      { icon: "broadcast", title: "Visual storytelling layout", description: "Present your destination/service experience clearly." },
      { icon: "framework", title: "Service and package structure", description: "Organize offers for faster user decisions." },
      { icon: "performance", title: "Mobile-first conversion UX", description: "Capture travel intent from on-the-go audiences." },
      { icon: "ecosystem", title: "Inquiry-ready lead flow", description: "WhatsApp and forms aligned to booking conversations." },
    ],
    benefitsTitle: "Why this improves tourism lead generation",
    benefitsSubtitle: "Clear structure and trust signals increase traveler conversion intent.",
    benefitItems: [
      { title: "More direct inquiries", description: "Reduce reliance on third-party platforms for conversion." },
      { title: "Better destination credibility", description: "Stronger digital presence builds trust faster." },
      { title: "Higher conversion from mobile visitors", description: "Mobile-first design supports real travel behavior." },
    ],
    faqs: [
      { question: "Can this support multiple tourism services?", answer: "Yes. We can structure pages by service category and intent." },
      { question: "Can we include multilingual-ready structure?", answer: "Yes. We build architecture that can scale into multilingual content." },
      { question: "Do you integrate WhatsApp for booking inquiries?", answer: "Yes. WhatsApp is a key conversion channel in this model." },
    ],
  }),
};

export const locationPageContent: Record<string, CoreServicePageContent> = {
  "punta-cana": buildEntityPage({
    slug: "punta-cana",
    metadataTitle: "Web Design in Punta Cana | Conversion-Focused Agency",
    metadataDescription: "Web design in Punta Cana for businesses that need more leads, stronger trust, and better local conversion.",
    h1: "Web design in Punta Cana for businesses that need more clients",
    heroBadge: "Location · Punta Cana",
    heroLineOne: "Web design in Punta Cana",
    heroLineTwo: "built for lead generation",
    heroSubtitle: "We help businesses in Punta Cana convert local and international traffic into qualified inquiries.",
    whoTitle: "Who we help in Punta Cana",
    whoSubtitle: "Built for tourism, real estate, and premium local services.",
    whoItems: [
      { title: "Real estate and villas", description: "Capture international buyer and rental inquiries with trust-first pages." },
      { title: "Restaurants and excursions", description: "Increase reservations and direct inquiry flow." },
      { title: "Clinics and premium services", description: "Strengthen authority and consultation conversion." },
    ],
    includesTitle: "Local-intent website architecture",
    includesSubtitle: "Designed for visibility, trust, and conversion in Punta Cana.",
    includeItems: [
      { icon: "broadcast", title: "Local service positioning", description: "Clarify your offer for local and tourist audiences." },
      { icon: "framework", title: "City-specific SEO structure", description: "Support search intent for Punta Cana-related queries." },
      { icon: "performance", title: "Mobile-first traveler UX", description: "Capture mobile traffic with faster load and CTA flow." },
      { icon: "ecosystem", title: "WhatsApp lead system", description: "Convert high-intent users into direct conversations." },
    ],
    benefitsTitle: "Why this works in Punta Cana",
    benefitsSubtitle: "Conversion-focused websites help local businesses compete on trust and speed.",
    benefitItems: [
      { title: "More qualified local leads", description: "Attract users searching for services in Punta Cana." },
      { title: "Stronger professional image", description: "Position your business as credible and premium online." },
      { title: "Better inquiry conversion", description: "Guide users to proposal, quote, and WhatsApp actions." },
    ],
    faqs: [
      { question: "Do you work with Punta Cana tourism businesses?", answer: "Yes. Tourism and service businesses are core focus segments." },
      { question: "Can you optimize for local Punta Cana searches?", answer: "Yes. We structure pages around city-level search intent." },
      { question: "Can we include WhatsApp as a main CTA?", answer: "Yes. WhatsApp is integrated as a primary conversion path." },
    ],
  }),
  "dominican-republic": buildEntityPage({
    slug: "dominican-republic",
    metadataTitle: "Web Design Dominican Republic | Professional Business Websites",
    metadataDescription: "Web design in the Dominican Republic for businesses focused on leads, visibility, and conversion.",
    h1: "Web design in the Dominican Republic for business growth",
    heroBadge: "Location · Dominican Republic",
    heroLineOne: "Web design Dominican Republic",
    heroLineTwo: "focused on lead generation",
    heroSubtitle: "Professional websites for businesses across the Dominican Republic that need more inquiries and better conversion.",
    whoTitle: "Who we help across the Dominican Republic",
    whoSubtitle: "For businesses expanding visibility and lead quality nationwide.",
    whoItems: [
      { title: "Regional service businesses", description: "Need stronger digital presence across multiple cities." },
      { title: "Growing local brands", description: "Need websites that support commercial growth and trust." },
      { title: "Multi-location operators", description: "Need scalable page systems for different markets." },
    ],
    includesTitle: "National-scale website framework",
    includesSubtitle: "Designed for local relevance and conversion across the country.",
    includeItems: [
      { icon: "broadcast", title: "Location-ready content structure", description: "Support city-based and regional search intent." },
      { icon: "framework", title: "Scalable page architecture", description: "Expand services and locations without design drift." },
      { icon: "performance", title: "Responsive conversion UX", description: "Capture intent from all major traffic sources." },
      { icon: "ecosystem", title: "Lead routing flow", description: "Convert inquiries to WhatsApp and form channels effectively." },
    ],
    benefitsTitle: "Why this helps Dominican businesses scale",
    benefitsSubtitle: "A conversion-ready digital foundation improves visibility and pipeline quality.",
    benefitItems: [
      { title: "Broader market visibility", description: "Reach buyers searching across the Dominican Republic." },
      { title: "Stronger conversion system", description: "Turn traffic into proposal and quote requests." },
      { title: "Ready for expansion", description: "Build once, scale by city and service over time." },
    ],
    faqs: [
      { question: "Can this support multiple cities?", answer: "Yes. We build architecture ready for city-level expansion." },
      { question: "Do you optimize for Dominican search intent?", answer: "Yes. We structure pages around local and national intent." },
      { question: "Can this include service and location hubs?", answer: "Yes. Hub-and-spoke structure is built into our approach." },
    ],
  }),
  santiago: buildEntityPage({
    slug: "santiago",
    metadataTitle: "Web Design Santiago | Websites Built for More Local Leads",
    metadataDescription: "Web design in Santiago for businesses that need more local inquiries, better trust, and stronger conversion.",
    h1: "Web design in Santiago for local business growth",
    heroBadge: "Location · Santiago",
    heroLineOne: "Web design Santiago",
    heroLineTwo: "for high-intent local leads",
    heroSubtitle: "We help Santiago businesses improve local trust, mobile experience, and inquiry conversion.",
    whoTitle: "Who we help in Santiago",
    whoSubtitle: "For local businesses that need predictable lead generation online.",
    whoItems: [
      { title: "Local service providers", description: "Need better local visibility and conversion pathways." },
      { title: "Professional firms", description: "Need stronger authority and consultation-focused websites." },
      { title: "Retail and hospitality brands", description: "Need mobile-first experiences for local demand." },
    ],
    includesTitle: "Santiago-focused website system",
    includesSubtitle: "Built to improve trust, clarity, and conversion for local buyers.",
    includeItems: [
      { icon: "broadcast", title: "Local messaging structure", description: "Position your service clearly for Santiago audiences." },
      { icon: "framework", title: "Intent-based page hierarchy", description: "Guide users into high-conversion sections." },
      { icon: "performance", title: "Mobile lead optimization", description: "Capture action from local mobile traffic." },
      { icon: "ecosystem", title: "Direct contact pathways", description: "Request Proposal and WhatsApp integrated across pages." },
    ],
    benefitsTitle: "Why this works for Santiago businesses",
    benefitsSubtitle: "Local-intent architecture improves both visibility and lead quality.",
    benefitItems: [
      { title: "More local inquiries", description: "Attract users actively searching in Santiago." },
      { title: "Better conversion confidence", description: "Trust-first structure improves form completion and contact." },
      { title: "Stronger digital positioning", description: "Stand out against generic local competitors." },
    ],
    faqs: [
      { question: "Can we target Santiago-specific keywords?", answer: "Yes. We build city-level SEO structure and page intent." },
      { question: "Do you support local service businesses?", answer: "Yes. Local service conversion is a core use case." },
      { question: "Can we include WhatsApp as primary action?", answer: "Yes. WhatsApp can be prioritized in high-intent sections." },
    ],
  }),
  miami: buildEntityPage({
    slug: "miami",
    metadataTitle: "Web Design Miami | Premium Conversion-Focused Websites",
    metadataDescription: "Premium web design in Miami for businesses that need stronger positioning, performance, and lead generation.",
    h1: "Web design in Miami for premium growth-focused businesses",
    heroBadge: "Location · Miami",
    heroLineOne: "Web design Miami",
    heroLineTwo: "for premium conversion performance",
    heroSubtitle: "We build premium websites for Miami businesses that need stronger positioning and more qualified leads.",
    whoTitle: "Who we help in Miami",
    whoSubtitle: "For businesses competing in high-demand, premium service markets.",
    whoItems: [
      { title: "Premium service brands", description: "Need stronger authority and conversion-focused user flow." },
      { title: "Real estate and legal firms", description: "Need trust-first pages for high-value leads." },
      { title: "Growth-focused teams", description: "Need measurable lead generation from website traffic." },
    ],
    includesTitle: "Premium website structure for Miami",
    includesSubtitle: "Built for brand authority, conversion quality, and local search intent.",
    includeItems: [
      { icon: "broadcast", title: "High-end visual hierarchy", description: "Position your brand with premium perception online." },
      { icon: "framework", title: "Offer clarity and CTA flow", description: "Guide users into proposal and quote actions." },
      { icon: "performance", title: "Speed and UX standards", description: "Deliver fast, smooth experiences on all devices." },
      { icon: "ecosystem", title: "Lead workflow integration", description: "Connect forms and WhatsApp to your sales process." },
    ],
    benefitsTitle: "Why this drives better results in Miami",
    benefitsSubtitle: "Premium markets demand stronger trust and clearer differentiation.",
    benefitItems: [
      { title: "Higher-value lead quality", description: "Attract prospects with stronger budget and intent fit." },
      { title: "Sharper competitive positioning", description: "Differentiate your offer in a crowded market." },
      { title: "More consistent inquiries", description: "Improve conversion from search and paid traffic." },
    ],
    faqs: [
      { question: "Can this support premium brand positioning?", answer: "Yes. Premium design and trust architecture are core priorities." },
      { question: "Do you optimize for Miami local intent?", answer: "Yes. We align pages with city-level search behavior and conversion goals." },
      { question: "Can this support multi-service firms?", answer: "Yes. We build scalable page systems for complex service catalogs." },
    ],
  }),
  orlando: buildEntityPage({
    slug: "orlando",
    metadataTitle: "Web Design Orlando | Lead Generation Websites for Local Services",
    metadataDescription: "Web design in Orlando for local service businesses that need more leads, bookings, and qualified inquiries.",
    h1: "Web design in Orlando for local service businesses",
    heroBadge: "Location · Orlando",
    heroLineOne: "Web design Orlando",
    heroLineTwo: "focused on local lead flow",
    heroSubtitle: "We build conversion-focused websites for Orlando businesses that need more qualified local inquiries.",
    whoTitle: "Who we help in Orlando",
    whoSubtitle: "For service businesses that rely on local trust and consistent inquiry volume.",
    whoItems: [
      { title: "Lawyers, clinics, and contractors", description: "Need stronger conversion from local search intent." },
      { title: "Home and professional services", description: "Need clear offers and direct contact pathways." },
      { title: "Multi-location service teams", description: "Need scalable local pages with consistent design system." },
    ],
    includesTitle: "Orlando-focused conversion architecture",
    includesSubtitle: "Built to increase local visibility and inquiry consistency.",
    includeItems: [
      { icon: "broadcast", title: "Local service page framework", description: "Organize services around local search behavior." },
      { icon: "framework", title: "Trust-driven conversion blocks", description: "Improve decision confidence and inquiry action." },
      { icon: "performance", title: "Mobile-first lead capture", description: "Capture high-intent users across devices." },
      { icon: "ecosystem", title: "WhatsApp and form system", description: "Speed up contact and reduce response friction." },
    ],
    benefitsTitle: "Why this improves Orlando lead generation",
    benefitsSubtitle: "Clear local relevance and conversion flow improve pipeline consistency.",
    benefitItems: [
      { title: "More local service inquiries", description: "Align pages to Orlando-specific high-intent searches." },
      { title: "Better conversion from mobile traffic", description: "Support immediate action from mobile-first users." },
      { title: "Stronger professional trust", description: "Improve perception and lead quality from first interaction." },
    ],
    faqs: [
      { question: "Can you target Orlando local keywords?", answer: "Yes. We build location-intent page structure by city." },
      { question: "Do you work with service businesses?", answer: "Yes. Local services are a primary focus segment." },
      { question: "Can we add multiple service pages over time?", answer: "Yes. The structure is built for scalable expansion." },
    ],
  }),
};
